import React from "react";

const Homepage = () => {
  return (
    <>
      <div>這是首頁，刷一排REACT</div>
      <div>
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
        REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT REACT
      </div>
    </>
  );
};

export default Homepage;
